# Site settings
title: site.title
email: youremailaddress@gmail.com
# description: are getting married
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

icon: fa-diamond # Font Awesome class for your site's icon

# Language settings
languages: ["en", "fr"] 
exclude_from_localizations: []
add_redirect: ["cwtch.html", "wysg.html"]
defaultLang: en
languageNames:
  fr: Français
  en: English


# Translation keys
# 01_ceremony:
#  title: 01_ceremony.title

# Social settings
facebook_url:
github_url:
gitlab_url: 
googleplus_url:
instagram_url:
linkedin_url: 
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown

sass:
style: compressed